version: "3.9"

services:
  postgres:
    container_name: postgres
    image: postgres:14.2
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - 5432:5432
    volumes: 
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # go:
  #   container_name: go
  #   build:
  #     context: .
  #   ports:
  #     - 3000:3000
  #   depends_on:
  #     postgres:
  #       condition: service_healthy # waiting until heathcheck of postgres is good

volumes:
  postgres_data: # persist database
            